apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: hello-deploy
  labels:
    app: hello-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-deploy
  template:
    metadata:
      labels:
        app: hello-deploy
    spec:
      containers:
        - name: hello-deploy
          image: 192.168.153.131:80/helloworld/helloworld:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    app: hello-deploy
  name: hello-deploy
spec:
  selector:
    app: hello-deploy
  ports:
  - port: 8088
    targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test
  name: hello-deploy
spec:
  ingressClassName: ingress
  rules:
  - host: hello.world.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hello-deploy
              port:
                number: 8088

