apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: test
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: test
spec:
  containers:
    - name: test-container
      image: nginx
      envFrom:
        - configMapRef:
            name: special-config
  restartPolicy: Never